---
title: "Decision Curve Analysis Tutorial"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.duplicate.label = "allow")
```

```{r, render, echo = FALSE, include=FALSE}
rmarkdown::render("dca-tutorial.Rmd",
                  params = list(language = "r"),
                  output_file = "dca-tutorial-r.html")
# rmarkdown::render("dca-tutorial.Rmd",
#                   params = list(language = "stata"),
#                   output_file = "dca-tutorial-stata.html")
# rmarkdown::render("dca-tutorial.Rmd",
#                   params = list(language = "sas"),
#                   output_file = "dca-tutorial-sas.html")
# rmarkdown::render("dca-tutorial.Rmd",
#                   params = list(language = "python"),
#                   output_file = "dca-tutorial-python.html")
```

Welcome to the tutorial for Decision Curve Analysis.
The tutorial is available in four languages.

### Please, select a language

```{r, child = 'language-table-chunk.Rmd'}
```

Icons from https://icon-icons.com
